### ISSUE TITLE
Add write access to Everyone team.

### ISSUE THREAD

**Issue by hsbt** [jenkinsci/rbenv-plugin#40]
@jenkinsci/everyone  I found to leave this repository from our teams. Anyone add this repository to `Everyone` team?

**Comment by samrocketman** [comment]
@hsbt since you maintain this plugin I recommend going to `#jenkins` on freenode.  A lot of the Jenkins CI admins hang out there and there's an IRC bot for maintenance tasks on the jenkinsci org.

**Comment by oleg-nenashev** [comment]
@hsbt @samrocketman 
The Write permission has been granted to Everyone. It's better to use INFRA tickets next time

**Comment by hsbt** [comment]
@samrocketman @oleg-nenashev Thank you for your action. I'm going to try submit tickets next time.
