### ISSUE TITLE
Handle environment with multiple build servers

### ISSUE THREAD

**Issue by watsoncj** [jenkinsci/rbenv-plugin#5]
Thanks for the great plugin!

I ran into a few issues when using this on a Jenkins system with multiple slaves.
- master server is configured with a different home directory than the slaves
- ruby version was reinstalled every time

These errors indicate the issue:

```
Install rbenv
$ bash -c "git clone git://github.com/sstephenson/rbenv.git ~/.rbenv"
fatal: destination path '/home/hudson/.rbenv' already exists and is not an empty directory.
Install ruby-build
$ bash -c "mkdir -p ~/.rbenv/plugins && cd ~/.rbenv/plugins && git clone       git://github.com/sstephenson/ruby-build.git"
fatal: destination path 'ruby-build' already exists and is not an empty directory.
Install 
```

The main issue is that `File.expand_path("~/.rbenv")` evaluates to the master home directory rather than the slave home directory. The wrapper is checking for the existence of each directory on the master server and then installing rbenv/ruby on the slave server.

I am almost done with a commit that ports the 3 directory checks into a bash script that is executed on the slave.

**Comment by RafaelaMachado** [comment]
Good morning friend, I have the following problem:
can help me solve?

$ git clone git://github.com/sstephenson/rbenv.git .rbenv
fatal: destination path '.rbenv' already exists and is not an empty directory.

**Comment by watsoncj** [comment]
It looks like you've already followed that step in the rbenv install process. You can either `rm ~/.rbenv` and retry the clone, or skip to the next step in the rbenv installation guide.

I'm not sure this is related to the Jenkins rbenv plugin that this repository is dedicated to. I'd suggest asking any further questions on stackoverflow or the rbenv github repo.

**Comment by RafaelaMachado** [comment]
So friend, managed to solve it happens that the rbenv had been installed through the "apt-get" and therefore the rbenv was installed for the entire system and it would always use the "sudo". Then, remove the installation and installed by the repository for just the current User only.

Thank you!
